### ISSUE TITLE
게시판 생성 기능 구현

### ISSUE THREAD

**Issue by yeonwoo1125** [progh2/hellogit10131#13]

**Comment by yeonwoo1125** [comment]
원래 남의 레포에 이슈 쓰면 삭제가 안되나요?............

**Comment by progh2** [comment]
딱 걸렸으... ㅎㅎ
이슈는 기본적으로 삭제가 아니라 기록을 남겨두자는 주의라서 ㅎㅎ

**Comment by progh2** [comment]
이슈 쓰면 이메일이 날아오기때문에 내용 수정해도 알 수가 있지 ㅎㅎ -_-+

**Comment by yeonwoo1125** [comment]
ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ
