### ISSUE TITLE
마크다운 연습하기

### ISSUE THREAD

**Issue by haezzang** [progh2/hellogit10131#17]
# 마크다운 연습하기!

> 배구 4판 뛰어서 너무 힘들어요 
## 내가 지를 물품 목록
* 멘보샤
* 타코야끼

## 박종성이랑 결혼하는 법
1. 연예인급 얼굴이 된다
2. 하이브에 들어간다
3. 엔하이픈 매니저가 된다
4. 종성이와 핑크빛 기류를 만든다
5. 끝

### 코드를 작성해보자
```c
#include<stdio.h>

  int main(){
  printf("Jay Handsome Guy!!!!");
  return 0;
}
```

```java
class Hello{
public static void main(string args[]){
 System.out.println("Hello")
 }
}
```

----

깃허브 페이지로 가고 싶다면 [여기](https://github.com/)를 누르세요

- [ ] 중간고사 공부!
- [ ] 아이티쇼 준비!

![엔하이픈 제이](https://img.wkorea.com/w/2021/12/style_61c19bfe189cf-539x700.jpg)

@0pyaq0 제 남편 봐주세요! [ea4a4a8](https://github.com/Mirim-CPU/Mugunghwa/commit/ea4a4a8268b300f91f0ed88782048e5cbbaed8d4)

**Comment by 0pyaq0** [comment]
굿, 굿,
