### ISSUE TITLE
마크다운 연습하기

### ISSUE THREAD

**Issue by 0pyaq0** [progh2/hellogit10131#18]
# 제목
>금강산도 식후경이다

## 내가 지를 물품 목록
* 전용 비행기
  * 헬기
* 항공모형
* 황금알을 낳는 거위

## 냉장고에 코끼리를 넣는 방법
1. 냉장고 문을 연다
2. 코끼리를 구한다
3. 냉장고에 코끼리를 넣는다
4. 냉장고 문을 닫는다

### 부부제목

여기서는 `java -v`를 실행하면 `버전`을 확인할 수 있습니다.
```
#include<stdio.h>
int main(){
 printf("Hello World!");
return 0;
)
```

[Github](https://github.com/)

3cd766bb3f85d204ce2c8fdb4b62f4880717d073 이 코드에서 블라블라

**Comment by akwls** [comment]
이진아 # 뒤에 띄어쓰기 해야된다~

**Comment by 0pyaq0** [comment]
> 이진아 # 뒤에 띄어쓰기 해야된다~

아잇참... 감사합니다 ^^

**Comment by haezzang** [comment]
멋져요

**Comment by 0pyaq0** [comment]
> 멋져요

굿 ~^^
